global using AlAnvar.Database.Table;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.UI.Xaml;
global using Nucs.JsonSettings;
global using Nucs.JsonSettings.Fluent;
global using Nucs.JsonSettings.Modulation;
global using Nucs.JsonSettings.Modulation.Recovery;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
